apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: susana-shop
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "mysql" # <- Este es el nombre del Service de MySQL que crearemos
  DB_PORT: "3306"
  DB_NAME: "susana_shop" # <- Actualizado para consistencia
  JWT_EXPIRES_IN: "7d"
  # Variables de email (vacÃ­as por ahora)
  EMAIL_HOST: ""
  EMAIL_PORT: "587"
  EMAIL_USER: ""
  EMAIL_PASSWORD: ""