apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: susana-shop
type: Opaque
stringData:
  # ⚠️ CAMBIAR en producción
  JWT_SECRET: "supersecreto_cambiar_en_produccion_2024"
  DB_USER: "tienda_user"
  # ⚠️ Contraseña más segura
  DB_PASSWORD: "TiendaPass2024!Secure"
  # Variables de email (vacías por ahora, puedes llenarlas después)
  EMAIL_USER: ""
  EMAIL_PASSWORD: ""