apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: susana-shop
type: Opaque
stringData:
  # Base de datos
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "susana_shop"
  DB_USER: "tienda_user"
  DB_PASSWORD: "TiendaPass2024!Secure"
  
  # JWT
  JWT_SECRET: "supersecreto_cambiar_en_produccion_2024"
  
  # Email (opcional)
  EMAIL_USER: ""
  EMAIL_PASSWORD: ""