apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: susana-shop
type: Opaque
stringData:
  # Contraseña de root para la BD
  root-password: "RootSecure2024!MySQL"
  # Contraseña del usuario de la app
  user-password: "TiendaPass2024!Secure" # <- Debe coincidir con app-secrets